#!/usr/bin/env bash
# release.sh — create a versioned release of pg_epanet
#
# Usage:
#   ./scripts/release.sh 0.1.0            # full release
#   ./scripts/release.sh 0.1.0-alpha.1    # pre-release (no upgrade script)
#   ./scripts/release.sh 0.1.0-rc.1       # release candidate
#
# What it does:
#   1. Validates the version and git state
#   2. Updates Cargo.toml
#   3. Generates sql/pg_epanet--<version>.sql via cargo pgrx schema
#   4. For full releases: generates a stub upgrade script from the previous version
#   5. Updates CHANGELOG.md (moves [Unreleased] content to the new version)
#   6. Runs the test suite
#   7. Commits, tags (vX.Y.Z or vX.Y.Z-pre), and offers to push

set -euo pipefail
cd "$(dirname "$0")/.."

# ── helpers ──────────────────────────────────────────────────────────────────

die()  { echo "error: $*" >&2; exit 1; }
info() { echo "  → $*"; }

# Semver-ish: major.minor.patch or major.minor.patch-prerelease
SEMVER_RE='^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?$'

is_prerelease() { [[ "$1" =~ - ]]; }

# Extract the bare X.Y.Z part (strips any pre-release suffix)
base_version() { echo "${1%%-*}"; }

today() { date +%Y-%m-%d; }

# ── argument check ────────────────────────────────────────────────────────────

VERSION="${1:-}"
[[ -n "$VERSION" ]] || die "usage: $0 <version>  (e.g. 0.1.0 or 0.1.0-alpha.1)"
[[ "$VERSION" =~ $SEMVER_RE ]] || die "invalid version '$VERSION' — expected semver like 0.1.0 or 0.1.0-alpha.1"

TAG="v${VERSION}"
SQL_FILE="sql/pg_epanet--${VERSION}.sql"

if is_prerelease "$VERSION"; then
    RELEASE_KIND="pre-release"
else
    RELEASE_KIND="release"
fi

echo ""
echo "pg_epanet ${RELEASE_KIND}: ${VERSION}"
echo ""

# ── git state check ───────────────────────────────────────────────────────────

info "checking git state"
git diff --quiet          || die "there are unstaged changes — commit or stash first"
git diff --cached --quiet || die "there are staged changes — commit first"
git tag | grep -q "^${TAG}$" && die "tag ${TAG} already exists"

# ── current version (from Cargo.toml) ────────────────────────────────────────

PREV_VERSION=$(grep '^version' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
info "current version in Cargo.toml: ${PREV_VERSION}"
PREV_SQL="sql/pg_epanet--${PREV_VERSION}.sql"

# ── 1. update Cargo.toml ─────────────────────────────────────────────────────

info "updating Cargo.toml: ${PREV_VERSION} → ${VERSION}"
sed -i '' "s/^version = \"${PREV_VERSION}\"/version = \"${VERSION}\"/" Cargo.toml
grep -q "^version = \"${VERSION}\"" Cargo.toml || die "failed to update version in Cargo.toml"

# ── 2. generate SQL schema ────────────────────────────────────────────────────

info "generating ${SQL_FILE}"
mkdir -p sql
cargo pgrx schema pg18 --features pg18 --no-default-features --out "${SQL_FILE}" 2>/dev/null \
    || { cargo pgrx schema pg18 --features pg18 --no-default-features > "${SQL_FILE}"; }

echo "     $(wc -l < "$SQL_FILE") lines written"

# ── 3. upgrade script (full releases only) ────────────────────────────────────

if ! is_prerelease "$VERSION" && [[ -f "$PREV_SQL" ]]; then
    UPGRADE_FILE="sql/pg_epanet--${PREV_VERSION}--${VERSION}.sql"
    info "generating upgrade script: ${UPGRADE_FILE}"
    cat > "$UPGRADE_FILE" << EOF
-- pg_epanet upgrade: ${PREV_VERSION} → ${VERSION}
-- Generated by scripts/release.sh on $(today)
--
-- Review this file carefully before shipping.
-- Add any new tables, columns, or schema changes below.
-- Functions are handled automatically by the diff below.

-- ── auto-generated function diff ─────────────────────────────────────────────
EOF
    # Extract lines that are new in the new schema (added functions/signatures)
    diff "$PREV_SQL" "$SQL_FILE" \
        | grep '^>' | sed 's/^> //' \
        >> "$UPGRADE_FILE" || true
    echo "     written (review before shipping)"

elif ! is_prerelease "$VERSION" && [[ ! -f "$PREV_SQL" ]]; then
    info "no previous SQL file found (${PREV_SQL}) — skipping upgrade script"
fi

# ── 4. update CHANGELOG ───────────────────────────────────────────────────────

info "updating CHANGELOG.md"
CHANGELOG="CHANGELOG.md"
DATE=$(today)

# Check that [Unreleased] has content to move
UNRELEASED_CONTENT=$(awk '/^## \[Unreleased\]/{found=1; next} found && /^## \[/{exit} found{print}' "$CHANGELOG" | grep -v '^[[:space:]]*$' || true)
[[ -n "$UNRELEASED_CONTENT" ]] || die "[Unreleased] section in CHANGELOG.md is empty — nothing to release"

# Replace the [Unreleased] section:
#   - Keep an empty [Unreleased] header at the top
#   - Insert the new versioned section below
python3 - "$CHANGELOG" "$VERSION" "$DATE" << 'PYEOF'
import sys, re

changelog_path, version, date = sys.argv[1], sys.argv[2], sys.argv[3]
text = open(changelog_path).read()

# Find the [Unreleased] block and the content inside it
unreleased_pat = re.compile(
    r'(## \[Unreleased\]\n)(.*?)(\n## \[)',
    re.DOTALL
)
m = unreleased_pat.search(text)
if not m:
    sys.exit("could not find [Unreleased] section followed by another section")

body = m.group(2)  # content between [Unreleased] and the next section

new_text = text[:m.start()] \
    + "## [Unreleased]\n\n---\n\n" \
    + f"## [{version}] — {date}\n" \
    + body \
    + m.group(3)   \
    + text[m.end():]

open(changelog_path, 'w').write(new_text)
print(f"     [{version}] section added")
PYEOF

# ── 5. run tests ─────────────────────────────────────────────────────────────

info "running test suite"
cargo pgrx test pg18 --features pg18 --no-default-features 2>&1 \
    | tail -5 \
    || die "tests failed — aborting release"

# ── 6. commit and tag ────────────────────────────────────────────────────────

info "staging files"
git add Cargo.toml Cargo.lock sql/ CHANGELOG.md pg_epanet.control

info "committing"
COMMIT_MSG="chore: release ${TAG}"
if is_prerelease "$VERSION"; then
    COMMIT_MSG="chore: pre-release ${TAG}"
fi
git commit -m "$COMMIT_MSG"

info "tagging ${TAG}"
if is_prerelease "$VERSION"; then
    git tag -a "$TAG" -m "Pre-release ${VERSION}"
else
    git tag -a "$TAG" -m "Release ${VERSION}"
fi

echo ""
echo "  ✓ ${RELEASE_KIND} ${TAG} prepared"
echo ""

# ── 7. push ──────────────────────────────────────────────────────────────────

read -r -p "  Push commit and tag to origin? [y/N] " PUSH
if [[ "${PUSH,,}" == "y" ]]; then
    git push origin HEAD
    git push origin "$TAG"
    echo "  ✓ pushed"
else
    echo "  Skipped. To push manually:"
    echo "      git push origin HEAD && git push origin ${TAG}"
fi

echo ""
