use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use chrono::Local;

use crate::changelog::{Version, close_unreleased_section};
use crate::github::create_github_release;

pub struct ReleaseOptions {
    pub version: Version,
    pub create_github_release: bool,
    pub github_release_only: bool,
    pub yes: bool,
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("xtask lives in repo root")
        .to_path_buf()
}

fn today() -> String {
    Local::now().format("%Y-%m-%d").to_string()
}

fn info(msg: &str) {
    println!("  → {msg}");
}

fn die(msg: impl AsRef<str>) -> ! {
    eprintln!("error: {}", msg.as_ref());
    std::process::exit(1);
}

fn confirm(prompt: &str) -> bool {
    print!("{prompt}");
    let _ = io::stdout().flush();
    let mut line = String::new();
    if io::stdin().read_line(&mut line).is_err() {
        return false;
    }
    matches!(line.trim().to_lowercase().as_str(), "y" | "yes")
}

fn git_quiet(root: &Path, args: &[&str]) {
    let status = Command::new("git")
        .args(args)
        .current_dir(root)
        .status()
        .unwrap_or_else(|e| die(format!("git failed: {e}")));
    if !status.success() {
        die(format!("git {} failed", args.join(" ")));
    }
}

fn ensure_clean(root: &Path) {
    info("checking git state");
    git_quiet(root, &["diff", "--quiet"]);
    git_quiet(root, &["diff", "--cached", "--quiet"]);
}

fn tag_exists(root: &Path, tag: &str) -> bool {
    Command::new("git")
        .args(["tag", "--list", tag])
        .current_dir(root)
        .output()
        .map(|o| {
            !String::from_utf8_lossy(&o.stdout)
                .lines()
                .any(|l| l.trim().is_empty())
                && String::from_utf8_lossy(&o.stdout).contains(tag)
        })
        .unwrap_or(false)
}

fn cargo_version(root: &Path) -> String {
    let text = fs::read_to_string(root.join("Cargo.toml")).expect("Cargo.toml");
    text.lines()
        .find(|l| l.starts_with("version = "))
        .and_then(|l| l.split('"').nth(1))
        .expect("version in Cargo.toml")
        .to_string()
}

fn set_cargo_version(root: &Path, prev: &str, new: &str) {
    let path = root.join("Cargo.toml");
    let text = fs::read_to_string(&path).expect("Cargo.toml");
    let updated = text.replace(
        &format!("version = \"{prev}\""),
        &format!("version = \"{new}\""),
    );
    if !updated.contains(&format!("version = \"{new}\"")) {
        die("failed to update version in Cargo.toml");
    }
    fs::write(&path, updated).expect("write Cargo.toml");
}

fn generate_sql(root: &Path, sql_file: &Path) {
    info(&format!("generating {}", sql_file.display()));
    fs::create_dir_all(root.join("sql")).ok();

    let mut cmd = Command::new("cargo");
    cmd.current_dir(root)
        .args([
            "pgrx",
            "schema",
            "pg18",
            "--features",
            "pg18",
            "--no-default-features",
            "--out",
            &sql_file.to_string_lossy(),
        ])
        .stderr(Stdio::null());

    if cmd.status().is_ok_and(|s| s.success()) {
        // ok
    } else {
        let output = Command::new("cargo")
            .current_dir(root)
            .args([
                "pgrx",
                "schema",
                "pg18",
                "--features",
                "pg18",
                "--no-default-features",
            ])
            .output()
            .expect("cargo pgrx schema");
        if !output.status.success() {
            die("cargo pgrx schema failed");
        }
        fs::write(sql_file, &output.stdout).expect("write sql");
    }

    let lines = fs::read_to_string(sql_file)
        .map(|s| s.lines().count())
        .unwrap_or(0);
    println!("     {lines} lines written");
}

fn generate_upgrade_script(
    prev_sql: &Path,
    new_sql: &Path,
    upgrade_file: &Path,
    prev_version: &str,
    version: &str,
) {
    info(&format!("generating upgrade script: {}", upgrade_file.display()));
    let header = format!(
        "-- pg_epanet upgrade: {prev_version} → {version}\n\
         -- Generated by xtask on {}\n\
         --\n\
         -- Review this file carefully before shipping.\n\
         -- Add any new tables, columns, or schema changes below.\n\
         -- Functions are handled automatically by the diff below.\n\
         \n\
         -- ── auto-generated function diff ─────────────────────────────────────────────\n",
        today()
    );
    fs::write(upgrade_file, header).expect("write upgrade header");

    let output = Command::new("diff")
        .arg(prev_sql)
        .arg(new_sql)
        .output()
        .expect("diff");

    let mut added = String::new();
    for line in String::from_utf8_lossy(&output.stdout).lines() {
        if let Some(rest) = line.strip_prefix('>') {
            if let Some(rest) = rest.strip_prefix(' ') {
                added.push_str(rest);
                added.push('\n');
            }
        }
    }
    fs::OpenOptions::new()
        .append(true)
        .open(upgrade_file)
        .and_then(|mut f| f.write_all(added.as_bytes()))
        .expect("append upgrade diff");
    println!("     written (review before shipping)");
}

fn update_changelog(root: &Path, version: &Version) {
    info("updating CHANGELOG.md");
    let path = root.join("CHANGELOG.md");
    let changelog = fs::read_to_string(&path).expect("CHANGELOG.md");
    let (new_changelog, _) =
        close_unreleased_section(&changelog, version, &today()).unwrap_or_else(|e| die(e));
    fs::write(&path, new_changelog).expect("write CHANGELOG.md");
    println!("     [{}] section added", version.text);
}

fn run_tests(root: &Path) {
    info("running test suite");
    let output = Command::new("cargo")
        .current_dir(root)
        .args([
            "pgrx",
            "test",
            "pg18",
            "--features",
            "pg18",
            "--no-default-features",
        ])
        .output()
        .expect("cargo pgrx test");
    for line in String::from_utf8_lossy(&output.stdout)
        .lines()
        .chain(String::from_utf8_lossy(&output.stderr).lines())
        .rev()
        .take(5)
        .collect::<Vec<_>>()
        .into_iter()
        .rev()
    {
        println!("{line}");
    }
    if !output.status.success() {
        die("tests failed — aborting release");
    }
}

pub fn run(opts: ReleaseOptions) -> Result<(), String> {
    let root = repo_root();
    let tag = opts.version.tag();
    let sql_file = root.join(format!("sql/pg_epanet--{}.sql", opts.version.text));
    let changelog_path = root.join("CHANGELOG.md");

    if opts.github_release_only {
        println!();
        println!("pg_epanet GitHub release: {tag}");
        println!();
        info("building release notes from CHANGELOG.md");
        let changelog = fs::read_to_string(&changelog_path).map_err(|e| e.to_string())?;
        create_github_release(&opts.version, &changelog, &changelog_path, false)?;
        println!();
        println!("  ✓ GitHub Release {tag} created");
        println!();
        return Ok(());
    }

    let release_kind = if opts.version.is_prerelease() {
        "pre-release"
    } else {
        "release"
    };

    println!();
    println!("pg_epanet {release_kind}: {}", opts.version.text);
    println!();

    ensure_clean(&root);
    if tag_exists(&root, &tag) {
        die(format!("tag {tag} already exists"));
    }

    let prev_version = cargo_version(&root);
    info(&format!("current version in Cargo.toml: {prev_version}"));
    let prev_sql = root.join(format!("sql/pg_epanet--{prev_version}.sql"));

    info(&format!(
        "updating Cargo.toml: {prev_version} → {}",
        opts.version.text
    ));
    set_cargo_version(&root, &prev_version, &opts.version.text);

    generate_sql(&root, &sql_file);

    if !opts.version.is_prerelease() {
        if prev_sql.is_file() {
            let upgrade_file = root.join(format!(
                "sql/pg_epanet--{prev_version}--{}.sql",
                opts.version.text
            ));
            generate_upgrade_script(
                &prev_sql,
                &sql_file,
                &upgrade_file,
                &prev_version,
                &opts.version.text,
            );
        } else {
            info(&format!(
                "no previous SQL file found ({}) — skipping upgrade script",
                prev_sql.display()
            ));
        }
    }

    update_changelog(&root, &opts.version);
    run_tests(&root);

    info("staging files");
    git_quiet(
        &root,
        &[
            "add",
            "Cargo.toml",
            "Cargo.lock",
            "sql/",
            "CHANGELOG.md",
            "pg_epanet.control",
        ],
    );

    info("committing");
    let commit_msg = if opts.version.is_prerelease() {
        format!("chore: pre-release {tag}")
    } else {
        format!("chore: release {tag}")
    };
    git_quiet(&root, &["commit", "-m", &commit_msg]);

    info(&format!("tagging {tag}"));
    let tag_msg = if opts.version.is_prerelease() {
        format!("Pre-release {}", opts.version.text)
    } else {
        format!("Release {}", opts.version.text)
    };
    git_quiet(&root, &["tag", "-a", &tag, "-m", &tag_msg]);

    println!();
    println!("  ✓ {release_kind} {tag} prepared");
    println!();

    let pushed = if opts.yes {
        git_quiet(&root, &["push", "origin", "HEAD"]);
        git_quiet(&root, &["push", "origin", &tag]);
        println!("  ✓ pushed");
        true
    } else if confirm("  Push commit and tag to origin? [y/N] ") {
        git_quiet(&root, &["push", "origin", "HEAD"]);
        git_quiet(&root, &["push", "origin", &tag]);
        println!("  ✓ pushed");
        true
    } else {
        println!("  Skipped. To push manually:");
        println!("      git push origin HEAD && git push origin {tag}");
        false
    };

    let create_release = if opts.yes {
        opts.create_github_release
    } else {
        let mut create = opts.create_github_release;
        if !create && pushed {
            create = confirm("  Create GitHub Release with CHANGELOG notes? [y/N] ");
        }
        create
    };

    if create_release {
        if !pushed {
            println!("  Note: tag must exist on GitHub before gh release create.");
            if !opts.yes && !confirm("  Continue anyway? [y/N] ") {
                die("aborted GitHub Release");
            }
        }
        info(&format!("creating GitHub Release {tag}"));
        let changelog = fs::read_to_string(&changelog_path).map_err(|e| e.to_string())?;
        create_github_release(&opts.version, &changelog, &changelog_path, false)?;
        println!("  ✓ GitHub Release {tag} created");
    }

    println!();
    Ok(())
}

pub fn close_unreleased(version: &Version, date: Option<&str>) -> Result<(), String> {
    let root = repo_root();
    let path = root.join("CHANGELOG.md");
    let changelog = fs::read_to_string(&path).map_err(|e| e.to_string())?;
    let today = today();
    let date = date.unwrap_or(&today);
    let (new_changelog, _) = close_unreleased_section(&changelog, version, date)?;
    fs::write(&path, new_changelog).map_err(|e| e.to_string())?;
    println!("     [{}] section added", version.text);
    Ok(())
}

pub fn print_release_notes(version: &Version, dry_run: bool) -> Result<(), String> {
    let root = repo_root();
    let changelog = fs::read_to_string(root.join("CHANGELOG.md")).map_err(|e| e.to_string())?;
    let notes = crate::changelog::release_notes(&changelog, version)?;
    if dry_run {
        print!("{notes}");
    } else {
        print!("{notes}");
    }
    Ok(())
}

pub fn github_release_only(version: &Version, dry_run: bool) -> Result<(), String> {
    let root = repo_root();
    let path = root.join("CHANGELOG.md");
    let changelog = fs::read_to_string(&path).map_err(|e| e.to_string())?;
    create_github_release(version, &changelog, &path, dry_run)
}
