-- pg_epanet upgrade: 0.2.0 → 0.2.1
-- Generated by xtask on 2026-06-25
--
-- Review this file carefully before shipping.
-- Add any new tables, columns, or schema changes below.
-- Functions are handled automatically by the diff below.

-- ── auto-generated function diff ─────────────────────────────────────────────
CREATE INDEX simulation_runs_network ON epanet.simulation_runs(network_id);


-- Endpoint lookups: pipes/pumps/valves joined to nodes by node1/node2
CREATE INDEX pipes_node1  ON epanet.pipes  (network_id, node1);
CREATE INDEX pipes_node2  ON epanet.pipes  (network_id, node2);
CREATE INDEX pumps_node1  ON epanet.pumps  (network_id, node1);
CREATE INDEX pumps_node2  ON epanet.pumps  (network_id, node2);
CREATE INDEX valves_node1 ON epanet.valves (network_id, node1);
CREATE INDEX valves_node2 ON epanet.valves (network_id, node2);
