/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/schema.rs:3
-- bootstrap

CREATE SCHEMA epanet;

CREATE TABLE epanet.networks (
    id          SERIAL PRIMARY KEY,
    name        TEXT NOT NULL,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    srid        INT NOT NULL,
    inp_text    TEXT NOT NULL
);

CREATE INDEX epanet_networks_name ON epanet.networks(name);

CREATE TABLE epanet.junctions (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    elevation   FLOAT8 NOT NULL,
    demand      FLOAT8 NOT NULL,
    pattern     TEXT,
    geom        geometry(Point),
    PRIMARY KEY (network_id, name)
);

CREATE TABLE epanet.reservoirs (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    head        FLOAT8 NOT NULL,
    pattern     TEXT,
    geom        geometry(Point),
    PRIMARY KEY (network_id, name)
);

CREATE TABLE epanet.tanks (
    network_id   INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    name         TEXT NOT NULL,
    elevation    FLOAT8 NOT NULL,
    init_level   FLOAT8 NOT NULL,
    min_level    FLOAT8 NOT NULL,
    max_level    FLOAT8 NOT NULL,
    diameter     FLOAT8 NOT NULL,
    min_volume   FLOAT8 NOT NULL,
    volume_curve TEXT,
    overflow     TEXT,
    geom         geometry(Point),
    PRIMARY KEY (network_id, name)
);

CREATE TABLE epanet.pipes (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    node1       TEXT NOT NULL,
    node2       TEXT NOT NULL,
    length      FLOAT8 NOT NULL,
    diameter    FLOAT8 NOT NULL,
    roughness   FLOAT8 NOT NULL,
    minor_loss  FLOAT8 NOT NULL,
    status      TEXT NOT NULL,
    geom        geometry(LineString),
    PRIMARY KEY (network_id, name)
);

CREATE TABLE epanet.pumps (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    node1       TEXT NOT NULL,
    node2       TEXT NOT NULL,
    pump_type   TEXT,
    head_curve  TEXT,
    power       FLOAT8,
    speed       FLOAT8,
    pattern     TEXT,
    geom        geometry(LineString),
    PRIMARY KEY (network_id, name)
);

CREATE TABLE epanet.valves (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    name        TEXT NOT NULL,
    node1       TEXT NOT NULL,
    node2       TEXT NOT NULL,
    diameter    FLOAT8 NOT NULL,
    valve_type  TEXT NOT NULL,
    setting     TEXT NOT NULL,
    minor_loss  FLOAT8 NOT NULL,
    geom        geometry(LineString),
    PRIMARY KEY (network_id, name)
);

CREATE TABLE epanet.coordinates (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    node_id     TEXT NOT NULL,
    x           FLOAT8 NOT NULL,
    y           FLOAT8 NOT NULL,
    PRIMARY KEY (network_id, node_id)
);

CREATE TABLE epanet.vertices (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    link_id     TEXT NOT NULL,
    idx         INT NOT NULL,
    x           FLOAT8 NOT NULL,
    y           FLOAT8 NOT NULL,
    PRIMARY KEY (network_id, link_id, idx)
);

CREATE VIEW epanet.nodes AS
    SELECT network_id, name AS node_id, 'junction'::text AS node_type, elevation, geom
      FROM epanet.junctions
    UNION ALL
    SELECT network_id, name, 'tank',      elevation, geom FROM epanet.tanks
    UNION ALL
    SELECT network_id, name, 'reservoir', head,      geom FROM epanet.reservoirs;

CREATE TABLE epanet.simulation_runs (
    id         SERIAL PRIMARY KEY,
    network_id INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    ran_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    n_steps    INT NOT NULL
);

CREATE TABLE epanet.node_results (
    run_id   INT NOT NULL REFERENCES epanet.simulation_runs(id) ON DELETE CASCADE,
    step     INT NOT NULL,
    node_id  TEXT NOT NULL,
    head     DOUBLE PRECISION,
    pressure DOUBLE PRECISION,
    demand   DOUBLE PRECISION,
    PRIMARY KEY (run_id, step, node_id)
);

CREATE INDEX node_results_run ON epanet.node_results(run_id);

CREATE TABLE epanet.link_results (
    run_id    INT NOT NULL REFERENCES epanet.simulation_runs(id) ON DELETE CASCADE,
    step      INT NOT NULL,
    link_id   TEXT NOT NULL,
    flow      DOUBLE PRECISION,
    velocity  DOUBLE PRECISION,
    headloss  DOUBLE PRECISION,
    PRIMARY KEY (run_id, step, link_id)
);

CREATE INDEX link_results_run ON epanet.link_results(run_id);

CREATE INDEX junctions_geom  ON epanet.junctions  USING GIST (geom);
CREATE INDEX reservoirs_geom ON epanet.reservoirs USING GIST (geom);
CREATE INDEX tanks_geom      ON epanet.tanks      USING GIST (geom);
CREATE INDEX pipes_geom      ON epanet.pipes      USING GIST (geom);
CREATE INDEX pumps_geom      ON epanet.pumps      USING GIST (geom);
CREATE INDEX valves_geom     ON epanet.valves     USING GIST (geom);

CREATE TABLE epanet.patterns (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    pattern_id  TEXT NOT NULL,
    idx         INT NOT NULL,
    multiplier  FLOAT8 NOT NULL,
    PRIMARY KEY (network_id, pattern_id, idx)
);

CREATE TABLE epanet.curves (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    curve_id    TEXT NOT NULL,
    idx         INT NOT NULL,
    x           FLOAT8 NOT NULL,
    y           FLOAT8 NOT NULL,
    PRIMARY KEY (network_id, curve_id, idx)
);

CREATE TABLE epanet.options (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.times (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.controls (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    idx         INT NOT NULL,
    rule_text   TEXT NOT NULL,
    PRIMARY KEY (network_id, idx)
);

CREATE TABLE epanet.rules (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    rule_id     TEXT NOT NULL,
    rule_text   TEXT NOT NULL,
    PRIMARY KEY (network_id, rule_id)
);

CREATE TABLE epanet.demands (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    junction_id TEXT NOT NULL,
    demand      FLOAT8 NOT NULL,
    pattern     TEXT,
    PRIMARY KEY (network_id, junction_id)
);

CREATE TABLE epanet.emitters (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    junction_id TEXT NOT NULL,
    coefficient FLOAT8 NOT NULL,
    PRIMARY KEY (network_id, junction_id)
);

CREATE TABLE epanet.status (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    link_id     TEXT NOT NULL,
    status_value TEXT NOT NULL,
    PRIMARY KEY (network_id, link_id)
);

CREATE TABLE epanet.sources (
    network_id   INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    node_id      TEXT NOT NULL,
    source_type  TEXT NOT NULL,
    quality      FLOAT8 NOT NULL,
    pattern      TEXT,
    PRIMARY KEY (network_id, node_id)
);

CREATE TABLE epanet.reactions (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.quality (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.energy (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.report (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:61
-- pg_epanet::metadata::epanet_controls
CREATE  FUNCTION "epanet_controls"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"idx" INT,  /* i32 */
	"rule_text" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_controls_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:480
-- pg_epanet::epanet_coordinates
CREATE  FUNCTION "epanet_coordinates"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"node_id" TEXT,  /* String */
	"x" double precision,  /* f64 */
	"y" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_coordinates_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:38
-- pg_epanet::metadata::epanet_curves
CREATE  FUNCTION "epanet_curves"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"curve_id" TEXT,  /* String */
	"idx" INT,  /* i32 */
	"x" double precision,  /* f64 */
	"y" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_curves_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:202
-- pg_epanet::epanet_delete
CREATE  FUNCTION "epanet_delete"(
	"network_id" INT /* i32 */
) RETURNS bool /* bool */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_delete_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:81
-- pg_epanet::metadata::epanet_demands
CREATE  FUNCTION "epanet_demands"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"junction_id" TEXT,  /* String */
	"demand" double precision,  /* f64 */
	"pattern" TEXT  /* Option < String > */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_demands_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:96
-- pg_epanet::metadata::epanet_emitters
CREATE  FUNCTION "epanet_emitters"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"junction_id" TEXT,  /* String */
	"coefficient" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_emitters_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:58
-- pg_epanet::metadata::epanet_energy
CREATE  FUNCTION "epanet_energy"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_energy_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:91
-- pg_epanet::epanet_import
CREATE  FUNCTION "epanet_import"(
	"network_name" TEXT, /* & str */
	"inp_text" TEXT, /* & str */
	"srid" INT DEFAULT 5367 /* i32 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_import_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:412
-- pg_epanet::epanet_junctions
CREATE  FUNCTION "epanet_junctions"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"name" TEXT,  /* String */
	"elevation" double precision,  /* f64 */
	"demand" double precision,  /* f64 */
	"pattern" TEXT  /* Option < String > */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_junctions_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:54
-- pg_epanet::metadata::epanet_options
CREATE  FUNCTION "epanet_options"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_options_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:20
-- pg_epanet::metadata::epanet_patterns
CREATE  FUNCTION "epanet_patterns"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"pattern_id" TEXT,  /* String */
	"idx" INT,  /* i32 */
	"multiplier" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_patterns_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:443
-- pg_epanet::epanet_pipes
CREATE  FUNCTION "epanet_pipes"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"name" TEXT,  /* String */
	"node1" TEXT,  /* String */
	"node2" TEXT,  /* String */
	"length" double precision,  /* f64 */
	"diameter" double precision,  /* f64 */
	"roughness" double precision,  /* f64 */
	"minor_loss" double precision,  /* f64 */
	"status" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_pipes_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:523
-- pg_epanet::epanet_pumps
CREATE  FUNCTION "epanet_pumps"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"name" TEXT,  /* String */
	"node1" TEXT,  /* String */
	"node2" TEXT,  /* String */
	"pump_type" TEXT,  /* Option < String > */
	"head_curve" TEXT,  /* Option < String > */
	"power" double precision,  /* Option < f64 > */
	"speed" double precision,  /* Option < f64 > */
	"pattern" TEXT  /* Option < String > */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_pumps_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:57
-- pg_epanet::metadata::epanet_quality
CREATE  FUNCTION "epanet_quality"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_quality_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:56
-- pg_epanet::metadata::epanet_reactions
CREATE  FUNCTION "epanet_reactions"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_reactions_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:59
-- pg_epanet::metadata::epanet_report
CREATE  FUNCTION "epanet_report"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_report_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:17
-- pg_epanet::epanet_reservoirs
CREATE  FUNCTION "epanet_reservoirs"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"name" TEXT,  /* String */
	"head" double precision,  /* f64 */
	"pattern" TEXT  /* Option < String > */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_reservoirs_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:73
-- pg_epanet::metadata::epanet_rules
CREATE  FUNCTION "epanet_rules"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"rule_id" TEXT,  /* String */
	"rule_text" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_rules_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:213
-- pg_epanet::epanet_simulate
CREATE  FUNCTION "epanet_simulate"(
	"network_id" INT /* i32 */
) RETURNS INT /* i32 */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_simulate_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:112
-- pg_epanet::metadata::epanet_sources
CREATE  FUNCTION "epanet_sources"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"node_id" TEXT,  /* String */
	"source_type" TEXT,  /* String */
	"quality" double precision,  /* f64 */
	"pattern" TEXT  /* Option < String > */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_sources_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:104
-- pg_epanet::metadata::epanet_status
CREATE  FUNCTION "epanet_status"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"link_id" TEXT,  /* String */
	"status_value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:39
-- pg_epanet::epanet_tanks
CREATE  FUNCTION "epanet_tanks"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"name" TEXT,  /* String */
	"elevation" double precision,  /* f64 */
	"init_level" double precision,  /* f64 */
	"min_level" double precision,  /* f64 */
	"max_level" double precision,  /* f64 */
	"diameter" double precision,  /* f64 */
	"min_volume" double precision,  /* f64 */
	"volume_curve" TEXT,  /* Option < String > */
	"overflow" TEXT  /* Option < String > */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_tanks_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:55
-- pg_epanet::metadata::epanet_times
CREATE  FUNCTION "epanet_times"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_times_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:586
-- pg_epanet::epanet_valves
CREATE  FUNCTION "epanet_valves"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"name" TEXT,  /* String */
	"node1" TEXT,  /* String */
	"node2" TEXT,  /* String */
	"diameter" double precision,  /* f64 */
	"valve_type" TEXT,  /* String */
	"setting" TEXT,  /* String */
	"minor_loss" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_valves_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:501
-- pg_epanet::epanet_vertices
CREATE  FUNCTION "epanet_vertices"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"link_id" TEXT,  /* String */
	"x" double precision,  /* f64 */
	"y" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_vertices_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:11
-- pg_epanet::hello_pg_epanet
CREATE  FUNCTION "hello_pg_epanet"() RETURNS TEXT /* & '_ str */
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'hello_pg_epanet_wrapper';
/* </end connected objects> */

