-- pg_epanet upgrade: 0.1.0 → 0.2.0
-- Generated by xtask on 2026-06-25
--
-- Review this file carefully before shipping.
-- Add any new tables, columns, or schema changes below.
-- Functions are handled automatically by the diff below.

-- ── auto-generated function diff ─────────────────────────────────────────────

CREATE TABLE epanet.patterns (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    pattern_id  TEXT NOT NULL,
    idx         INT NOT NULL,
    multiplier  FLOAT8 NOT NULL,
    PRIMARY KEY (network_id, pattern_id, idx)
);

CREATE TABLE epanet.curves (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    curve_id    TEXT NOT NULL,
    idx         INT NOT NULL,
    x           FLOAT8 NOT NULL,
    y           FLOAT8 NOT NULL,
    PRIMARY KEY (network_id, curve_id, idx)
);

CREATE TABLE epanet.options (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.times (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.controls (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    idx         INT NOT NULL,
    rule_text   TEXT NOT NULL,
    PRIMARY KEY (network_id, idx)
);

CREATE TABLE epanet.rules (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    rule_id     TEXT NOT NULL,
    rule_text   TEXT NOT NULL,
    PRIMARY KEY (network_id, rule_id)
);

CREATE TABLE epanet.demands (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    junction_id TEXT NOT NULL,
    demand      FLOAT8 NOT NULL,
    pattern     TEXT,
    PRIMARY KEY (network_id, junction_id)
);

CREATE TABLE epanet.emitters (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    junction_id TEXT NOT NULL,
    coefficient FLOAT8 NOT NULL,
    PRIMARY KEY (network_id, junction_id)
);

CREATE TABLE epanet.status (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    link_id     TEXT NOT NULL,
    status_value TEXT NOT NULL,
    PRIMARY KEY (network_id, link_id)
);

CREATE TABLE epanet.sources (
    network_id   INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    node_id      TEXT NOT NULL,
    source_type  TEXT NOT NULL,
    quality      FLOAT8 NOT NULL,
    pattern      TEXT,
    PRIMARY KEY (network_id, node_id)
);

CREATE TABLE epanet.reactions (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.quality (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.energy (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);

CREATE TABLE epanet.report (
    network_id  INT NOT NULL REFERENCES epanet.networks(id) ON DELETE CASCADE,
    key         TEXT NOT NULL,
    value       TEXT NOT NULL,
    PRIMARY KEY (network_id, key)
);
-- src/metadata.rs:61
-- pg_epanet::metadata::epanet_controls
CREATE  FUNCTION "epanet_controls"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"idx" INT,  /* i32 */
	"rule_text" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_controls_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:480
-- src/metadata.rs:38
-- pg_epanet::metadata::epanet_curves
CREATE  FUNCTION "epanet_curves"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"curve_id" TEXT,  /* String */
	"idx" INT,  /* i32 */
	"x" double precision,  /* f64 */
	"y" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_curves_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:202
-- src/metadata.rs:81
-- pg_epanet::metadata::epanet_demands
CREATE  FUNCTION "epanet_demands"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"junction_id" TEXT,  /* String */
	"demand" double precision,  /* f64 */
	"pattern" TEXT  /* Option < String > */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_demands_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:96
-- pg_epanet::metadata::epanet_emitters
CREATE  FUNCTION "epanet_emitters"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"junction_id" TEXT,  /* String */
	"coefficient" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_emitters_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:58
-- pg_epanet::metadata::epanet_energy
CREATE  FUNCTION "epanet_energy"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_energy_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:91
-- src/lib.rs:412
-- src/metadata.rs:54
-- pg_epanet::metadata::epanet_options
CREATE  FUNCTION "epanet_options"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_options_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:20
-- pg_epanet::metadata::epanet_patterns
CREATE  FUNCTION "epanet_patterns"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"pattern_id" TEXT,  /* String */
	"idx" INT,  /* i32 */
	"multiplier" double precision  /* f64 */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_patterns_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:443
-- src/lib.rs:523
-- src/metadata.rs:57
-- pg_epanet::metadata::epanet_quality
CREATE  FUNCTION "epanet_quality"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_quality_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:56
-- pg_epanet::metadata::epanet_reactions
CREATE  FUNCTION "epanet_reactions"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_reactions_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:59
-- pg_epanet::metadata::epanet_report
CREATE  FUNCTION "epanet_report"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_report_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:17
-- src/metadata.rs:73
-- pg_epanet::metadata::epanet_rules
CREATE  FUNCTION "epanet_rules"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"rule_id" TEXT,  /* String */
	"rule_text" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_rules_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:213
-- src/metadata.rs:112
-- pg_epanet::metadata::epanet_sources
CREATE  FUNCTION "epanet_sources"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"node_id" TEXT,  /* String */
	"source_type" TEXT,  /* String */
	"quality" double precision,  /* f64 */
	"pattern" TEXT  /* Option < String > */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_sources_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/metadata.rs:104
-- pg_epanet::metadata::epanet_status
CREATE  FUNCTION "epanet_status"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"link_id" TEXT,  /* String */
	"status_value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_status_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:39
-- src/metadata.rs:55
-- pg_epanet::metadata::epanet_times
CREATE  FUNCTION "epanet_times"(
	"inp_text" TEXT /* & str */
) RETURNS TABLE (
	"key" TEXT,  /* String */
	"value" TEXT  /* String */
)
STRICT
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'epanet_times_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:586
-- src/lib.rs:501
-- src/lib.rs:11
