-- pg_epanet upgrade: 0.1.0-rc.1 → 0.1.0
-- Generated by scripts/release.sh on 2026-06-24
--
-- Review this file carefully before shipping.
-- Add any new tables, columns, or schema changes below.
-- Functions are handled automatically by the diff below.

-- ── auto-generated function diff ─────────────────────────────────────────────
